# Generated by Django 5.1.1 on 2024-12-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gen',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='localitate',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='strada',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tara',
            field=models.CharField(blank=True),
        ),
    ]
