# Generated by Django 5.1.1 on 2024-12-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie', '0004_vizualizari'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField()),
                ('data_creare', models.DateTimeField(auto_now_add=True)),
                ('data_expirare', models.DateTimeField()),
                ('subiect', models.CharField(blank=True, null=True)),
                ('mesaj', models.TextField(blank=True, null=True)),
                ('reducere', models.DecimalField(decimal_places=1, max_digits=3)),
                ('categorie', models.CharField(choices=[('liric', 'Liric'), ('epic', 'Epic')])),
            ],
        ),
        migrations.AddField(
            model_name='carte',
            name='categorie',
            field=models.CharField(choices=[('liric', 'Liric'), ('epic', 'Epic'), ('dramatic', 'Dramatic'), ('nonliteral', 'Nonliterar')], default='epic'),
        ),
    ]
