# Generated by Django 5.1.1 on 2024-12-18 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie', '0005_promotii_carte_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotii',
            name='categorie',
        ),
    ]
