# Generated by Django 5.1.1 on 2025-01-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie', '0008_customuser_blocat'),
    ]

    operations = [
        migrations.AddField(
            model_name='carte',
            name='nr_stoc',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
